version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    env_file:
      - cmd/auction/.env
    command: sh -c "/auction"
    networks:
      - localNetwork
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - cmd/auction/.env
    volumes:
      - mongo-data:/data/db
    networks:
      - localNetwork
    healthcheck:
      test: |
        mongosh --username $$MONGO_INITDB_ROOT_USERNAME --password $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  mongo-data:
    driver: local

networks:
  localNetwork:
    driver: bridge